name: CI/CD Workflow for Hotel Management System

# Trigger workflow on push or pull request to the "dev" branch and allow manual runs
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  # Job for building and testing the backend
  backend:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Python environment for backend testing
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install backend dependencies
      - name: Install Backend Dependencies
        run: |
          pip install -r backend/requirements.txt

      # Run backend tests
      - name: Run Backend Tests
        run: |
          cd backend
          pytest

  # Job for building and testing the frontend
  frontend:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install frontend dependencies
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      # Run frontend tests
      - name: Run Frontend Tests
        run: |
          npm test

  # Job for deployment (optional, if applicable)
  deploy:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Deploy the application (example placeholder commands)
      - name: Deploy Application
        run: |
          echo "Deploying application..."
          # Add your deployment commands here
